---
  -
    hosts: client-ansible-31

    tasks:
      - name: Set installation variable for centos
        set_fact:
          webserver_application_port: 80
          webserver_application_path: /usr/share/www
          webserver_application_user: root
        when: ansible_distribution == 'CentOS'

      - name: Show pre-set distrbution besd facts
        debug:
          msg: "webserver_application_path:{{ webserver_application_path}} webserver_application_port:{{webserver_application_port}}  webserver_application_user:{{ webserver_application_user }}"
...
