---
-
  hosts: all


  tasks:
    - name: USing template, creatin a remote file taht contains all variable available
      template:
        src: templates/dump_variables
        dest: /tmp/ansible_variables

    - name: Fetch the templatefile with all variable. beck to the control hosts
      fetch:
        src: /tmp/ansible_variables
        dest: "captured_variables/{{ ansible_hostname }}"
        flat: yes

    - name: Clean up
      file:
        name: /tmp/ansible_variables
        state: absent
