---
# YAML documents begin with the document separator ---

# The minus in YAML this indicates a list item.  The playbook contains a list
# of plays, with each play being a dictionary
-

  # Target: where our play will run and options it will run with
  hosts: client

  # Variable: variables that will apply to the play, on all target systems


  # Task: the list of tasks that will be executed within the playbook
  tasks:
    - name: Creating users
      user:
        name: "{{ item.key }}"
        comment: "{{ item.value.full_name}}"
      with_dict:
        james:
          full_name: James Spurin
        hayley:
          full_name: Hayley Spurin
        lily:
          full_name: Lily Spurin
        anwen:
          full_name: Anwen Spurin      

# Three dots indicate the end of a YAML document
...
