---
  -
    hosts: client-ansible-31

    tasks:
      - name: Set facts
        set_fact:
          our_fact: Ansible Rocks!

      - name: Show custom fact
        debug:
          msg: "{{ our_fact }}"
...
