---
  -
    # target
    hosts: all

    # tasks:
    tasks:
      - name: Make Facts Dir
        file:
          path: /home/AdminSYS/ansible/facts.d
          recurse: yes
          state: directory
          owner: AdminSYS

      - name: Copy Fact 1
        copy:
          src: facts.d/getdate1.fact
          dest: /home/AdminSYS/ansible/facts.d/getdate1.fact
          owner: AdminSYS
          mode: 0755

      - name: Copy Fact 2
        copy:
          src: facts.d/getdate2.fact
          dest: /home/AdminSYS/ansible/facts.d/getdate2.fact
          owner: AdminSYS
          mode: 0755

      - name: Reload Facts
        setup:
          fact_path: /home/AdminSYS/ansible/facts.d

      - name: Show Ip Address
        debug:
          msg: "{{ ansible_default_ipv4.address }}"

      - name: Show custom fact 1
        debug:
          msg: "{{ ansible_local.getdate1.date }}"
      - name: Show custom fact 2
        debug:
          msg: "{{ ansible_local.getdate2.date.date }}"
      - name: Show Custom Fact 1 in hostvars
        debug:
          msg: "{{ hostvars[ansible_hostname].ansible_local.getdate1.date }}"

      - name: Show Custom Fact 2 in hostvars
        debug:
          msg: "{{hostvars[ansible_hostname].ansible_local.getdate2.date.date }}"
...
