---
-
  # target
  hosts: client-ansible-34
  gather_facts: true

  #variables

  # tasks
  tasks:
    - name: test hostvar with an ansible fact and collecct ansible port dot notation
      debug:
        msg: "{{ hostvars[ansible_hostname].ansible_port }}"

    - name: test hostvar with an ansible fact and collecct ansible port dict notation
      debug:
        msg: "{{ hostvars[ansible_hostname]['ansible_port'] }}"
...
