---
-
  # target
  hosts: client-ansible-31
  gather_facts: true

  #variables

  # tasks
  tasks:
    - name: Test hostvars with an ansible fact and collect ansible_port, dot notation
      debug:
        msg: "{{ hostvars[ansible_hostname].ansible_port }}"

    - name: Test groupvars
      debug:
        msg: "{{ ansible_user }}"
...
