---
-
  # target
  hosts: client
  gather_facts: true

  #variables

  # tasks
  tasks:
    - name: Test hostvars with an ansible fact and collect ansible_port, dot notation
      debug:
        msg: "{{ hostvars[ansible_hostname].ansible_port | default('22') }}"

    - name: Test groupvars
      debug:
        msg: "{{ ansible_user }}"
...
