---

# the minus indictges a list item, the playbook contain a lsits of ,
#with each play being a dictionary
-

  # Target
  hosts: client


  # tasks: list of tasks that will be executed within the plays
  # can also be pre and post tasks
  tasks:
    - name: Exploring register
      command: hostname -s
      when:
        - ansible_distribution == "CentOS"
        - ansible_distribution_major_version | int >= 7
      register: command_register

    - name: Show register
      debug:
        var: command_register
...
