---
  -
    # target
    hosts: all

  # Tasks:
    tasks:
      - name: Nsible Jinja2 if varaible is defined
        debug:
          msg: >
                --== Ansible Jinja2 if vairable is defined ==--

                  {% if example_variable is defined -%}
                          example_variable is defined
                  {% else -%}
                       example_variable is not defined       
                  {% endif %}
...
