---
  -

    hosts: client


    tasks:
      - name: Exploring register
        command: hostname -s
        register: hostname_output

      - name: show hostname_output
        debug:
          var: hostname_output

...
